# Generated by Django 2.0.4 on 2018-04-18 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.PositiveSmallIntegerField(default=5)),
                ('cells', models.PositiveSmallIntegerField(default=5)),
                ('mines', models.PositiveSmallIntegerField(default=3)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
