# Generated by Django 2.0.4 on 2018-04-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grids', '0002_grid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
