# Generated by Django 2.0.4 on 2018-04-18 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bomb', models.BooleanField(default=False)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grids.Grid')),
            ],
        ),
    ]
