# Generated by Django 2.0.4 on 2018-04-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_auto_20180418_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
